# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

OrdererOrgs:
  - Name: Lucas
    Domain: lucas.com
    EnableNodeOUs: true
    Specs:
      - Hostname: ordenador

PeerOrgs:
  - Name: Hospital
    Domain: hospital.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Cliente
    Domain: cliente.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
