version: '2'

volumes:
  ordenador.lucas.com:
  peer0.hospital.com:
  peer1.hospital.com:
  peer0.cliente.com:
  peer1.cliente.com:

networks:
  minharede:

services:

  ordenador.lucas.com:
    extends:
      file: base/docker-compose-base.yaml
      service: ordenador.lucas.com
    container_name: ordenador.lucas.com
    networks:
      - minharede

  peer0.hospital.com:
    container_name: peer0.hospital.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.hospital.com
    networks:
      - minharede

  peer1.hospital.com:
    container_name: peer1.hospital.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.hospital.com
    networks:
      - minharede
  
  peer0.cliente.com:
    container_name: peer0.cliente.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.cliente.com
    networks:
      - minharede
  
  peer1.cliente.com:
    container_name: peer1.cliente.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.cliente.com
    networks:
      - minharede

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=sysmeucanal
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.hospital.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hospital.com/peers/peer0.hospital.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hospital.com/peers/peer0.hospital.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hospital.com/peers/peer0.hospital.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hospital.com/users/Admin@hospital.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - ordenador.lucas.com
      - peer0.hospital.com
      - peer1.hospital.com
      - peer0.cliente.com
      - peer1.cliente.com
    networks:
      - minharede